{% set name = "ffmpy" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ffmpy-{{ version }}.tar.gz
  sha256: 757591581eee25b4a50ac9ffb9b58035a2794533db47e0512f53fb2d7b6f9adc

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - pip
    - ffmpeg
  run:
    - python
    - ffmpeg

test:
  imports:
    - ffmpy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Ch00k/ffmpy
  summary: A simple Python wrapper for ffmpeg
  description: |
    ffmpy is a simple FFmpeg command line wrapper.
    It implements a Pythonic interface for FFmpeg command line compilation
    and uses Python's subprocess to execute the compiled command line.
  license: MIT
  license_file: LICENSE
  license_family: MIT
  doc_url: https://ffmpy.readthedocs.io/
  dev_url: https://github.com/Ch00k/ffmpy

extra:
  recipe-maintainers:
    - MattTriano
